<!DOCTYPE html>
<!--
Cart Project with MVC
Charles S. Lobe-Manga <charles@lobe-manga.com> 
-->
<html>
    <head>
        <title><?php echo Config::get('site_name');?></title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet"> 
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        
        <script src="/js/admin.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <body>
        <?php $router = App::getRouter(); ?>
        
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                  <a class="navbar-brand" href="/<?php echo $router->getLanguage(); ?>">
                    <?php echo Config::get( 'site_name' ) . ' - ' . translate( 'lng.admin.title', 'Admin Section' ); ?>  
                  </a>
              </div>
              <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    
                    <li <?php if( $router->getController() == 'articles' && $router->getAction() == 'index' ) { ?>
                        class="active"<?php } ?> >
                        <a href="/admin"><?php echo translate( 'lng.nav.home' ); ?></a></li>
                    
               
                    <li <?php if( $router->getController() == 'users' && $router->getAction() == 'register' ) { ?>
                        class="active"<?php } ?> >
                        <a href="/admin/users/register"><?php echo translate( 'lng.nav.register' ); ?></a></li>
                    
                    <li <?php if( $router->getController() == 'users' && $router->getAction() == 'index' ) { ?>
                        class="active"<?php } ?> >
                        <a href="/admin/users"><?php echo translate( 'lng.nav.users' ); ?></a></li>
                    
                    <li <?php if( $router->getController() == 'pages' && $router->getAction() == 'index' ) { ?>
                        class="active"<?php } ?> >
                        <a href="/admin/pages"><?php echo translate( 'lng.nav.pages' ); ?></a></li>
                    
                    
                    <li <?php if( $router->getController() == 'contacts') { ?>class="active"<?php } ?>>
                       <a href="/admin/contacts">
                            <?php echo translate( 'lng.nav.contact' ); ?></a></li>
                    
                    <li <?php if( $router->getController() == 'users' && $router->getAction() == 'logout' ) { ?>
                        class="active"<?php } ?> >
                        <a href="/users/logout"><?php echo translate( 'lng.nav.logout' ); ?></a></li>
                    
                </ul>
              </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            <div class="starter-template">
              
            <?php if( Session::hasFlash() ) { ?>
                <div class="alert alert-info" role="alert">
                    <?php Session::flash(); ?>
                </div>
            </div>
            <?php } ?>
      
            <?php echo $data['content'] ?>
            
          </div>
        </div>
    </body>
</html>