<?php
use Application\Lib\Config;
use Application\Lib\App;
use Application\Lib\Session;
?>
<!DOCTYPE html>
<!--
Cart Project with MVC
Charles S. Lobe-Manga <charles@lobe-manga.com> 
-->
<html>
   <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?php echo Config::get('site_name');?></title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Comfortaa|Lato">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        <script type="text/javascript" src="/js/admin.js"></script>
    </head>
    <body class="w3-light-grey">
        <?php $router = App::getRouter(); ?>
        
        <div class="w3-content" style="max-width: 1400px;">
            <div class="w3-bar w3-black w3-text-sand w3-border w3-card-2">
                <div class="w3-left bar-item-admin">
                    <a class="w3-bar-item" href="/<?php echo $router->getLanguage(); ?>">
                      <?php echo Config::get( 'site_name' ) . ' - ' . 
                              translate( 'lng.admin.title', 'Admin Section' ); ?>  
                    </a>
                </div>
                
                <div class="w3-left bar-item-custom">
                    <a class="w3-bar-item w3-button w3-padding-large" 
                        <?php if( $router->getController() == 'articles' && $router->getAction() == 'index' ) { ?>
                        class="active"<?php } ?>
                        href="/admin"><?php echo translate( 'lng.nav.home' ); ?>
                    </a>

                    <a class="w3-bar-item w3-button w3-padding-large" 
                        <?php if( $router->getController() == 'users' && $router->getAction() == 'index' ) { ?>
                        class="active"<?php } ?>
                        href="/admin/users"><?php echo translate( 'lng.nav.users' ); ?>
                    </a>

                    <a class="w3-bar-item w3-button w3-padding-large" 
                        <?php if( $router->getController() == 'pages' && $router->getAction() == 'index' ) { ?>
                        class="active"<?php } ?>
                        href="/admin/pages"><?php echo translate( 'lng.nav.pages' ); ?>
                    </a>

                    <a class="w3-bar-item w3-button w3-padding-large" 
                        <?php if( $router->getController() == 'contacts') { ?>class="active"<?php } ?>
                        href="/admin/contacts"><?php echo translate( 'lng.nav.contactss', 'Messages' ); ?>
                    </a>

                    <a class="w3-bar-item w3-button w3-padding-large" 
                        <?php if( $router->getController() == 'users' && $router->getAction() == 'logout' ) { ?>
                        class="active"<?php } ?>
                        href="/users/logout"><?php echo translate( 'lng.nav.logout' ); ?>
                    </a>
                </div><!--/.nav-collapse -->
            </div>

            <div class="w3-container">
                
                <?php if( Session::hasFlash() ) { ?>
                    <div class="alert alert-info" role="alert">
                        <?php Session::flash(); ?>
                    </div>
                <?php } ?>

                <?php echo $data[ 'dynamic' ]['content']; ?>
            
            </div>
        </div>
    </body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</html>