<?php
use Application\Lib\Config;
use Application\Lib\App;
?>
<!DOCTYPE html>
<!--
Cart Project with MVC
Charles S. Lobe-Manga <charles@lobe-manga.com>
-->
<html>
    <head>
        <title><?php echo Config::get('site_name');?></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Comfortaa">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" type="text/css" href="/css/style.css">
    </head>
    <body>
        <?php
            $router     = App::getRouter();
            $lang       = $router->getLanguage();
            $controller = $router->getController();
            $action     = $router->getAction();
        ?>
        <div class="w3-bar w3-top w3-black w3-card-2">
            <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>

            <span class="w3-bar-item w3-button w3-padding-large company"><?php echo Config::get('site_name'); ?></span>

            <a class="w3-bar-item w3-button w3-padding-large"
            <?php if( $controller == 'articles' && $action == 'index') { echo " active"; } ?>
                href="/<?php echo $lang; ?>"><?php echo translate( 'lng.nav.home' ); ?>
            </a>

            <?php if( !isset( $_SESSION['user'] ) ) { ?>

            <a class="w3-bar-item w3-button w3-padding-large"
            <?php if( $controller == 'users' && $action == 'login' ) { echo " active"; } ?>
                href="/<?php echo $lang; ?>/users/login"><?php echo translate( 'lng.nav.login' ); ?>
            </a>

           <a class="w3-bar-item w3-button w3-padding-large"
           <?php if( $controller == 'users' && $action == 'register' ) { echo " active"; } ?>
                href="/<?php echo $lang; ?>/users/register"><?php echo translate( 'lng.nav.register' ); ?>
           </a>

            <?php } else { ?>

            <a class="w3-bar-item w3-button w3-padding-large"
            <?php if( $controller == 'articles' && $action == 'add') { echo " active"; } ?>
                href="/<?php echo $lang; ?>/articles/add"><?php echo translate( 'lng.nav.article.add' ); ?>
            </a>

            <a class="w3-bar-item w3-button w3-padding-large"
            <?php if( $controller == 'users') { echo " active"; } ?>
                <a href="/<?php echo $lang; ?>/users/logout"><?php echo translate( 'lng.nav.logout' ); ?>
            </a>

            <?php } ?>

            <a class="w3-bar-item w3-button w3-padding-large"
            <?php if( $controller == 'contacts') { echo " active"; } ?>
                href="/<?php echo $lang; ?>/contacts">
                    <?php echo translate( 'lng.nav.contact' ); ?>
            </a>
        </div>

        <div class="w3-panel">
            <div class="w3-row-padding">
                <div class="w3-threequarter w3-container">

                    <?php echo $data[ 'dynamic' ]['content']; ?>

                </div>
        
                <div class="w3-quarter w3-container">

                <?php
                $static_pages = $data[ 'static' ];

                foreach ( $static_pages as $page ) {

                    $file_name = LANG_PATH .DS. $lang .DS. $page['Alias'] . '.txt';

                    if( file_exists( $file_name ) ) {
                ?>

                <div>

                    <a href="/<?php echo $lang; ?>/pages/view/<?php echo $page['Alias']; ?>">
                        <?php echo $page['Title']; ?>
                    </a>

                </div>

                <?php } } ?>

                <br>
                
                <div>
                  <h4>Archives</h4>
                  <ol class="list-unstyled">
                    <li><a href="#">March 2014</a></li>
                    <li><a href="#">February 2014</a></li>
                    <li><a href="#">January 2014</a></li>
                    <li><a href="#">December 2013</a></li>
                    <li><a href="#">November 2013</a></li>
                    <li><a href="#">October 2013</a></li>
                    <li><a href="#">September 2013</a></li>
                    <li><a href="#">August 2013</a></li>
                    <li><a href="#">July 2013</a></li>
                    <li><a href="#">June 2013</a></li>
                    <li><a href="#">May 2013</a></li>
                    <li><a href="#">April 2013</a></li>
                  </ol>
                </div>
                <br>
                <div>
                  <h4>Elsewhere</h4>
                  <ol class="list-unstyled">
                    <li><a href="#">GitHub</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                  </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="w3-container w3-bottom w3-black">
      <p>Copyright &copy; <?php echo date('Y'); ?> Charles S. Lobe-Manga</p>
    </div>

    </body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</html>
