<h4><b>Articles Control</b></h4>

<table class="table table-striped table-bordered admin-table-articles">
    
    <tr>
        <td style="width: 5%">#</td>
        <td style="width: 20%">Title</td>
        <td style="width: 10%">Author</td>
        <td style="width: 35%">Content</td>
        <td style="width: 15%">Last changed</td>
        <td style="width: 15%"></td>
    </tr>
    
    <?php
    $count = 1;
    
    foreach ( $data as $article ) { 
        
        $content = substr( $article['Content'], 0, Config::get( 'content_length' ) );
    
        $date_article = new DateTime( $article['DatePublished'] );
        $df = date_format( $date_article, 'd M Y' ) . '<br>' . 
        date_format( $date_article, 'H:i T' ); 
    ?>
    <tr>
        <td><?php echo $count; ?></td>
        
        <td><?php echo $article['Title']; ?></td>
        
        <td><?php echo $article['Login']; ?></td>
        
        <td><?php echo $content . ' ...'; ?></td>
        
        <td><?php echo $df; ?></td>
        
        
        <td class="admin-table">
            <a href="/admin/articles/edit/<?php echo $article['ArticleId']; ?>">
                <button class="btn btn-sm btn-primary">Edit</button></a>
                
            <a href="/admin/articles/delete/<?php echo $article['ArticleId']; ?>" onclick="return confirmDelete();" >
                <button class="btn btn-sm btn-warning">Delete</button></a>
        </td>
    </tr>
    <?php $count++; } ?>
    
</table>

<br>

<div>
    <a href="/admin/articles/add/"
       <button class="btn btn-sm btn-success">New Page</button>
    </a>
</div>
