<?php
use Application\Lib\Config;

$lang = $data['language'];
?>
<div class="w3-content" style="max-width: 1400px">
    <div class="w3-container w3-padding-large w3-margin w3-responsive">
        
        <h4><b>Articles Control</b></h4>
        <hr>

        <table class="w3-table-all w3-hoverable w3-small w3-card-4" style="width: 90%">
            <tr class="w3-dark-gray w3-text-sand">
                <th style="width: 5%">#</th>
                <th class="w3-border" style="width: 20%">Title</th>
                <th style="width: 10%">Author</th>
                <th class="w3-border" style="width: 35%">Content</th>
                <th style="width: 10%">Published</th>
                <th class="w3-border w3-center" style="width: 7%">Active</th>
                <th class="w3-white" style="width: 13%"></th>
            </tr>

            <?php
            $count = 1;

            foreach ( $data['articles'] as $article ) { 

                $content = substr( $article['Content'], 0, Config::get( 'content_length' ) );

                $date_article = new DateTime( $article['DatePublished'] );
                $df = date_format( $date_article, 'd M Y' ) . '<br>' . 
                date_format( $date_article, 'H:i' ); 
            ?>
            <tr>
                <td><?php echo str_pad($article['ArticleId'], 3, '0', STR_PAD_LEFT); ?></td>

                <td class="w3-border"><?php echo $article['Title']; ?></td>

                <td><?php echo $article['Login']; ?></td>

                <td class="w3-border"><?php echo $content . ' ...'; ?></td>

                <td class="w3-padding-4"><?php echo $df; ?></td>

                <td class="w3-border w3-center"><?php echo $article['IsPublished']; ?></td>

                <td class="admin-table">
                    <a href="/admin/<?php echo $lang; ?>/articles/edit/<?php echo $article['ArticleId']; ?>">
                        <button class="w3-button w3-blue w3-round-xlarge w3-text-sand">Edit</button>
                    </a>

                    <a href="/admin/<?php echo $lang; ?>/articles/delete/<?php echo $article['ArticleId']; ?>" 
                            onclick="return confirmDelete();" >
                        <button class="w3-button w3-orange w3-round-xlarge w3-text-sand">Delete</button>
                    </a>
                </td>
            </tr>
            <?php $count++; } ?>

        </table>

        <br>

        <div>
            <a href="/admin/<?php echo $lang; ?>/articles/add/"
               <button class="w3-button w3-green w3-round-xlarge w3-text-sand">New Article</button>
            </a>
        </div>
    </div>
</div>
