<div class="blog-header">
    <h1 class="blog-title">Der Maintaler Blog</h1>
    <p class="lead blog-description">Template for creating MVC with PHP</p>
</div>

<?php 

  foreach ( $data['articles'] as $article ) { 
    
    $date_article = new DateTime( $article['DatePublished'] ); ?>

<div class="blog-post">
    <h3 class="blog-post-title"><?php echo $article['Title']; ?></h3>
    
    <p class="blog-post-meta">
        Published on <?php echo date_format( $date_article, 'd M Y' ); ?> at 
        <?php echo date_format( $date_article, 'G:h T' ); ?> 
        by <a href="#"><?php echo $article['Login']; ?></a></p>

    <p><?php echo substr( $article['Content'], 0, 200 ); ?></p>
    
    <nav>
        <ul class="pager">
            <li><a href="/articles/view/<?php echo $article['ArticleId']; ?>">Weiterlesen</a></li>
        </ul>
     </nav>
</div>
<?php } ?>