<?php 
  $lang = $data['language'];
  
  foreach ( $data['articles'] as $article ) { 
    
      $article_id   = $article['ArticleId'];
      $article_link = "/$lang/articles/view/$article_id";
      
    $date_article = new DateTime( $article['DatePublished'] ); ?>

<div class="w3-card-4 blog-item w3-margin" style="width: 95%">
    
    <div class="w3-container w3-dark-grey w3-text-sand w3-padding-medium">
        <h4><?php echo $article['Title']; ?></h4>
    </div>
    
    <div class="w3-container w3-border">
        <p class="w3-padding-4 w3-margin">
            
            Published <?php echo dateIsToday( $date_article ) ? 
                '<b>Today</b>' : 'on' . date_format( $date_article, 'd M Y' ); ?> at 
            <?php echo date_format( $date_article, 'G:h T' ); ?> by&nbsp;
            
            <span class="w3-tag w3-black"><a href="#"><?php echo $article['Login']; ?></a></span>
        </p>
    </div>

    <div class="w3-container">
        <p class="w3-padding-4 w3-margin"><?php echo $article['Content']; ?></p>
        <p>
            <a href="<?php echo $article_link ?>">
                <button class="w3-button w3-right w3-padding-4 w3-border w3-black w3-text-sand w3-round-xlarge">
                Weiterlesen
                </button>
            </a>
        </p>
    </div>
</div>
<hr>
<?php } ?>