<?php
use Application\Lib\Session;

$article = $data['article'];
$author = $data['author'];
$comments = $data['comments'];

$date_article = new DateTime($article['DatePublished']);
$logged_in = ( Session::get('user') != null );
?>

<div class="w3-content" style="max-width: 800px;">
    
    <h2><?php echo $article['Title']; ?></h2>

    <p>
        Published on <b><?php echo date_format($date_article, 'd M Y'); ?></b> at 
    <?php echo date_format($date_article, 'G:h T'); ?> 
        by <a href="#"><?php echo $author['Login']; ?></a></p>
    
    <hr>

    <p><?php echo $article['Content']; ?></p>

    <!--Comments section-->

    <?php if (!count($comments)) { ?>
        <p>Be the first to comment on this article.</p>
    <?php } else { ?>
        <p>
            <br><br>
            <b>Comments: </b><span class="w3-tag w3-black"><?php echo count($comments); ?></span></p>
    <?php } ?>

    <form method="post" action="">
        <div class="w3-row">
            <div class="w3-col m2">
                <input type="hidden" name="comment_id" id="comment_id" 
                       value="<?php echo $comment['CommentId'] ?? ''; ?>" />

                <textarea class="form-control" id="content" name="content" rows="4" cols="50"
                          placeholder="Your comment" value="<?php echo $comment['Content'] ?? ''; ?>"
    <?php if (!$logged_in) echo 'disabled'; ?> width="100%">
                </textarea>
            </div>
            <div class="w3-col m10">
                <button type="submit" class="w3-button w3-dark-gray w3-right">OK</button>
            </div>
        </div>
    </form>

    <?php foreach ($comments as $comment) { ?>
        <div class="comment row">
            <div class="col-xs-2">
                <img src="http://gravatar.com/avatar/<?php echo md5($comment['Content']); ?>" width="5%" >
            </div>
            <div class="col-xs-10">
                <p><?php echo $comment['Content']; ?></p>
            </div>
        </div>
    <?php } ?>

</div>





