<h4><b>Pages Control</b></h4>

<table class="table table-striped table-bordered admin-table-pages">
    
    <tr>
        <td style="width: 5%">#</td>
        <td style="width: 20%">Alias</td>
        <td style="width: 40%">Title</td>
        <td style="width: 10%">Published</td>
        <td style="width: 25%"></td>
    </tr>
    
<?php foreach ( $data['pages'] as $article ) { ?>
    <tr>
        <td><?php echo $article['PageId']; ?></td>
        
        <td><?php echo $article['Alias']; ?></td>
        
        <td><?php echo $article['Title']; ?></td>
        
        <td><?php echo $article['IsPublished']; ?></td>
        
        
        <td class="admin-table">
            <a href="/admin/pages/edit/<?php echo $article['PageId']; ?>">
                <button class="btn btn-sm btn-primary">Edit</button></a>
                
            <a href="/admin/pages/delete/<?php echo $article['PageId']; ?>" onclick="return confirmDelete();" >
                <button class="btn btn-sm btn-warning">Delete</button></a>
        </td>
    </tr>
<?php } ?>
</table>

<br>

<div>
    <a href="/admin/pages/add/"
       <button class="btn btn-sm btn-success">New Page</button>
    </a>
</div>