<?php
    $page = $data['page'];
 ?>

<div class="w3-container w3-margin w3-teal w3-text-sand" style="width: 60%">
    <h3>Edit page</h3>
</div>

<div class="w3-card-4 w3-container w3-margin" style="width: 60%">
    <form method="post" action="" class="w3-container w3-margin">

        <input type="hidden" name="page_id" value="<?php echo $page['PageId']; ?>" >

        <label for="title">Title</label>
        <input type="text"  name="title" value="<?php echo $page['Title']; ?>" 
               class="w3-input w3-border" />
        <hr>

        <label for="alias">Alias</label>
        <input type="text" name="alias" value="<?php echo $page['Alias']; ?>" 
               class="w3-input w3-border" disabled="disabled" />
        <hr>
        
        <label for="is_published">Publish</label>
        <input type="checkbox" class="w3-check" name="is_published" 
            <?php if( $page['IsPublished'] == 1 ) { echo 'checked="checked"'; } ?> >
        <hr>

        <input type="submit" class="w3-button w3-blue w3-round-xlarge w3-text-sand" 
               value="<?php echo translate( 'lng.form.btn.update', 'OK' ); ?>" />    
    </form>
</div>