<div class="w3-container w3-margin w3-teal w3-text-sand" style="width: 60%">
    <h3>New Page</h3>
</div>

<div class="w3-card-4 w3-container w3-margin" style="width: 60%">
    <form method="post" action="" class="w3-container w3-margin">

        <label for="title">Title</label>
        <input type="text"  name="title" class="w3-input w3-border" />
        <hr>

        <label for="alias">Alias</label>
        <input type="text" id="alias" name="alias" class="w3-input w3-border" />
        <hr>
        
        <label for="is_published">Publish</label>
        <input type="checkbox" class="w3-check" name="is_published" >
        <hr>

        <input type="submit" class="w3-button w3-blue w3-round-xlarge w3-text-sand" 
               value="<?php echo translate( 'lng.form.submit', 'OK' ); ?>" />    
    </form>
</div>