<div class="w3-content" style="max-width: 1400px">

    <div class="w3-container w3-padding-large w3-margin w3-responsive">
        
        <h4><b>Pages Control</b></h4>
        <hr>

        <table class="w3-table-all w3-small w3-card-4 w3-hoverable" style="width:60%">

            <tr class="w3-dark-gray w3-text-sand">
                <td style="width: 5%">#</td>
                <td style="width: 20%">Alias</td>
                <td style="width: 40%">Title</td>
                <td style="width: 10%">Published</td>
                <td style="width: 25%"></td>
            </tr>

        <?php foreach ( $data['pages'] as $article ) { ?>
            <tr>
                <td><?php echo $article['PageId']; ?></td>

                <td><?php echo $article['Alias']; ?></td>

                <td><?php echo $article['Title']; ?></td>

                <td class="w3-center"><?php echo $article['IsPublished']; ?></td>

                <td class="admin-table">
                    <a href="/admin/pages/edit/<?php echo $article['PageId']; ?>">
                        <button class="w3-button w3-blue w3-round-xlarge w3-text-sand">Edit</button></a>

                    <a href="/admin/pages/delete/<?php echo $article['PageId']; ?>" onclick="return confirmDelete();" >
                        <button class="w3-button w3-orange w3-round-xlarge w3-text-sand">Delete</button></a>
                </td>
            </tr>
        <?php } ?>
        </table>

        <br>

        <div>
            <a href="/admin/pages/add/"
               <button class="w3-button w3-green w3-round-xlarge w3-text-sand">New Page</button>
            </a>
        </div>
    </div>
</div>