<?php
    $lang = $data['language'];
?>
<div class="w3-content" style="max-width: 1400px;">
    
    <div class="w3-container w3-padding-large w3-margin w3-responsive">

        <h4><b>Users Control</b></h4>
        <hr>

        <table class="w3-table-all w3-small w3-card-4 w3-hoverable admin-table-users">

            <tr class="w3-dark-gray w3-text-sand">
                <td style="width: 8%">User-Id</td>
                <td class="w3-border" style="width:22%">Login</td>
                <td style="width: 35%">Email</td>
                <td class="w3-border" style="width:7%">Admin</td>
                <td style="width: 7%">Active</td>
                <td class="w3-white" style="width:30%"></td>
            </tr>

            <?php foreach ( $data['users'] as $user) { ?>
            <tr>
                <td class="w3-center"><?php echo str_pad( $user['UserId'], 3, '0', STR_PAD_LEFT ); ?></td>

                <td class="w3-border"><?php echo $user['Login']; ?></td>

                <td><?php echo $user['Email']; ?></td>

                <td class="w3-center w3-border"><?php echo $user['Role']; ?></td>

                <td class="w3-center w3-border"><?php echo $user['IsActive']; ?></td>

                <td class="w3-center">
                    <a href="/admin/<?php echo $lang; ?>/users/edit/<?php echo $user['UserId']; ?>">
                        <button class="w3-button w3-blue w3-round-xlarge w3-text-sand">Edit</button></a>

                    <a href="/admin/<?php echo $lang; ?>/users/delete/<?php echo $user['UserId']; ?>" 
                       onclick="return confirmDelete();" >
                        <button class="w3-button w3-orange w3-round-xlarge w3-text-sand">Delete</button></a>
                </td>
            </tr>
            <?php } ?>
        </table>

        <br>

        <div>
            <a href="/admin/<?php echo $lang; ?>/users/add/"
               <button class="w3-button w3-green w3-round-xlarge w3-text-sand">New User</button></a>
        </div>
    </div>
</div>