<h3>Register</h3>

<br>

<form method="post" action="">
    
    <div class="form-group">
        <label for="login">Login</label>
        <input type="text" id="login" name="login" 
               class="form-control" required="required" />
    </div>
    
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" id="password" name="password" 
               class="form-control" required="required" />
    </div>
    
    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" id="email" name="email" 
               class="form-control" required="required" />
    </div>
        
    <input type="submit" class="btn btn-primary" />
</form>


