<h3>Edit User</h3>

<br>

<form method="post" action="">
    
    <input type="hidden" name="user_id" value="<?php echo $data['user']['UserId']; ?>" >
    
    <div class="form-group">
        <label for="login">Login</label>
        <input type="text" id="login" name="login" 
               value="<?php echo $data['user']['Login']; ?>"
               class="form-control" required="required"  disabled="disabled"/>
    </div>
    
    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" id="email" name="email" 
               value="<?php echo $data['user']['Email']; ?>"
               class="form-control" required="required" disabled="disabled"/>
    </div>
    
    <div class="form-group">
        <label for="role">Admin</label>
        <input type="checkbox" id="role" name="role" 
        <?php if( $data['user']['Role'] == 1 ) echo 'checked="checked"'; ?> />
    </div>
    
    <div class="form-group">
        <label for="is_active">Active</label>
        <input type="checkbox" id="is_active" name="is_active" 
        <?php if( $data['user']['IsActive'] == 1 ) echo 'checked="checked"'; ?> />
    </div>
        
    <input type="submit" class="btn btn-success" 
           value="<?php echo translate( 'lng.form.btn.update', 'OK' ); ?>" />
</form>
