<div class="w3-card-4 user-form login">
    
    <div class="w3-container w3-dark-gray w3-text-sand">
        <h4>Login</h4> 
    </div>

    <form method="post" action="" class="w3-container">

        <label>Benutzer</label>
        <input type="text" id="login" name="login" autofocus="autofocus"
               class="w3-input" required="required" />

        <label>Passwort</label>
        <input type="password" id="password" name="password" 
               class="w3-input" required="required" />
        <br>
        
        <button type="submit" class="w3-btn w3-dark-gray">
                <?php echo translate( 'lng.form.btn.send', 'OK' ); ?>
        </button>
    </form>
</div>