<div class="w3-card-4 user-form w3-margin">
    
    <div class="w3-container w3-dark-gray w3-text-sand">
        <h4>Register</h4> 
    </div>

    <form method="post" action="">
        <div class="w3-container">
            <p class="w3-margin">
            <label for="login">Benutzer</label>
            <input type="text" id="login" name="login" autofocus="autofocus"
                   class="w3-input" required="required" />

            <label>Passwort</label>
            <input type="password" id="password" name="password" 
                   class="w3-input" required="required" />

            <label>Email</label>
            <input type="email" id="password" name="email" 
                   class="w3-input" required="required" />
            <br>

            <button type="submit" class="w3-button w3-dark-gray">
                    <?php echo translate( 'lng.form.btn.register', 'OK' ); ?>
            </button>
            </p>
        </div>
    </form>
</div>

