<h3>Messages</h3>

<table class="table table-striped">
    
    <tr>
        <td style="width: 5%">#</td>
        <td style="width: 10%">Name</td>
        <td style="width: 25%">Email</td>
        <td style="width: 50%">Message</td>
    </tr>
    
    <?php foreach ( $data as $item ) { ?>
    <tr>
        <td><?php echo $item['MessageId']; ?></td>
        <td><?php echo $item['Name']; ?></td>
        <td><?php echo $item['Email']; ?></td>
        <td><?php echo $item['Message']; ?></td>
    </tr> 
    <?php } ?>
</table>